// src/ui/pages/BasePage.tsx
import React from "react";
import { twMerge } from "tailwind-merge";
import clsx from "clsx";
import PageHeader from "@ui/pages/PageHeader";
import PageFooter from "@ui/pages/PageFooter";

export type BasePageProps = {
  rootClassName?: string
  className?: string
  children: React.ReactNode
}

export default function BasePage(props: BasePageProps): React.ReactElement {
  return (
     <div className={clsx(
        'w-full min-h-screen flex justify-center',
        'px-2 md:px-6 py-2'
     )}>
       <div className={twMerge(
          'w-full mx-auto max-w-3xl',
          'space-y-3.5',
          props.rootClassName
       )}>
         <PageHeader />
         <main className={twMerge('py-2', props.className)}>
           {props.children}
         </main>
         <PageFooter />
       </div>
     </div>
  )
}

// web/src/lib/components/page/BasePage.svelte
<script lang="ts">
  import { cn } from '$lib/utils';
  import PageFooter from '$lib/components/page/PageFooter.svelte';
  import PageHeader from '$lib/components/page/PageHeader.svelte';

  export let rootClass: string | undefined = undefined;
  let className: string | undefined = undefined;
  export let showLogout: boolean = false;
  export { className as class };
</script>

<div class="w-full min-h-screen flex justify-center px-2 md:px-6 py-2">
  <div class={cn('w-full mx-auto max-w-3xl space-y-3.5', rootClass)}>
    <PageHeader {showLogout} />
    <main class={cn('py-2', className)}>
      <slot />
    </main>
    <PageFooter />
  </div>
</div>
