// web/src/routes/login/+page.svelte
<script lang="ts">
  import PageFooter from '$lib/components/page/PageFooter.svelte';
  import Logo from '$lib/assets/logo.png';
  import * as Form from '$lib/components/ui/form';
  import { formSchema, type FormSchema } from './schema';
  import type { SuperValidated } from 'sveltekit-superforms';

  export let form: SuperValidated<FormSchema>;
</script>

<div class={'w-full min-h-screen flex justify-center px-2 md:px-6 py-2'}>
  <div class={'w-full mx-auto max-w-3xl flex flex-col items-center gap-y-3.5'}>
    <header class={'flex items-center gap-x-2 text-3xl font-medium py-4'}>
      <img src={Logo} alt="WireAdmin" width="40" height="40" />
      <h1>WireAdmin</h1>
    </header>
    <main class={'py-4'}>
      <div class="w-full bg-white rounded-lg shadow-sm">
        <Form.Root method="POST" {form} schema={formSchema} let:config class="p-4 space-y-8">
          <div class="w-full flex items-center justify-center">
            <div class="w-16 aspect-square flex items-center justify-center rounded-full bg-gray-200">
              <i class="fas fa-user text-primary text-2xl" />
            </div>
          </div>

          <Form.Field {config} name="password">
            <Form.Item>
              <Form.Label>Password</Form.Label>
              <Form.Input type="password" autocomplete="off" />
              <Form.Validation />
            </Form.Item>
          </Form.Field>

          <Form.Button class="w-full">Sign In</Form.Button>
        </Form.Root>
      </div>
    </main>
    <PageFooter />
  </div>
</div>

// src/pages/login.tsx
import { signIn } from "next-auth/react";
import PageFooter from "@ui/pages/PageFooter";
import React from "react";
import Image from "next/image";
import { Button, Form, Input } from "antd";

export default function LoginPage() {

  const [ form ] = Form.useForm()

  async function handleFinish({ password }: { password: string | undefined }) {
    if (!password) {
      return form.resetFields()
    }

    await signIn(
       'credentials',
       { callbackUrl: '/' },
       { password }
    )
  }

  return (
     <div className={'w-full min-h-screen flex justify-center px-2 md:px-6 py-2'}>
       <div className={'w-full mx-auto max-w-3xl flex flex-col items-center gap-y-3.5'}>
         <header className={'flex items-center gap-x-2 text-3xl font-medium py-4'}>
           <Image
              src={'/logo.png'}
              alt={'WireAdmin'}
              width={40}
              height={40}
           />
           <h1> WireAdmin </h1>
         </header>
         <main className={'py-4'}>
           <Form
              form={form}
              onFinish={handleFinish}
              rootClassName={'bg-white rounded-lg shadow-sm'}
              className={'p-4 space-y-8'}
           >
             <div className={'flex items-center justify-center'}>
               <div className={'w-16 aspect-square flex items-center justify-center rounded-full bg-gray-200'}>
                 <i className={'fas fa-user text-primary text-2xl'} />
               </div>
             </div>
             <Form.Item name={'password'}>
               <Input placeholder={'Password...'} />
             </Form.Item>
             <Button block={true} onClick={form.submit}> Sign In </Button>
           </Form>
         </main>
         <PageFooter />
       </div>
     </div>
  );
}
